### ISSUE TITLE
10.15.2用一段时间,特别卡

### ISSUE THREAD

**Issue by PromiseNev** [mtjo/MacStroke#10]
用一天,就特别卡,整个电脑掉帧,多桌面四指滑动切换,卡到爆,然后重启app,恢复正常

**Comment by mtjo** [comment]
请提供一下版本号,不知道你的问题是不是和这个一样https://github.com/mtjo/MacStroke/issues/8,这个问题已经在最新的版本修复了

**Comment by PromiseNev** [comment]
1.0.8 ,我的问题就是正常使用,没外接任何显示器,主要问题是,我多屏幕,然后四指滑动,切屏幕,巨卡,巨卡,卡好几秒,突然有反应,然后关掉手势,再打开app,就正常了,用个把小时,又卡了,感觉是程序有内存泄露

**Comment by mtjo** [comment]
> 1.0.8 ,我的问题就是正常使用,没外接任何显示器,主要问题是,我多屏幕,然后四指滑动,切屏幕,巨卡,巨卡,卡好几秒,突然有反应,然后关掉手势,再打开app,就正常了,用个把小时,又卡了,感觉是程序有内存泄露

没重现出来,我系统osx:10.15.2  macstroke:1.0.9

**Comment by PromiseNev** [comment]
https://www.dropbox.com/s/cd58jie71geoyf4/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B62020-01-02%E4%B8%8B%E5%8D%886.21.44.mov?dl=0

我录了个屏,我四指滑动了2下,一开始没动静,然后卡了一会,2个屏幕,一次性滑动完了,关掉软件,流畅滑动  顺便...1.0.9版本?我能测试一波吗

**Comment by mtjo** [comment]
https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化
