### ISSUE TITLE
1.0.7 版本模拟右键时间长了不大好用

### ISSUE THREAD

**Issue by baonanhai** [mtjo/MacStroke#12]
时间长了，白天使用后，晚上锁屏，白天再使用，时不时就会发现在intelij他们家的应用下右键就不怎么好用了，重启下可以。
mac 系统版本
![image](https://user-images.githubusercontent.com/1573149/71613067-3976a680-2bdf-11ea-90fc-8074bc3d4308.png)

**Comment by mtjo** [comment]
> 时间长了，白天使用后，晚上锁屏，白天再使用，时不时就会发现在intelij他们家的应用下右键就不怎么好用了，重启下可以。
> mac 系统版本
> ![image](https://user-images.githubusercontent.com/1573149/71613067-3976a680-2bdf-11ea-90fc-8074bc3d4308.png)

1.0.7存在一个内存泄漏,新版本已经修复了
