### ISSUE TITLE
感觉使用之后，系统右键变得很卡很难出现了。

### ISSUE THREAD

**Issue by JJ7539** [mtjo/MacStroke#15]
在系统文件夹下，或者选择某个文件，或者在浏览器里复制某个文本……
都变得反正特别慢特别卡，有时要点第一次要等个1-2秒，或者不断的再点右键第二次菜单才会出现……
崩溃啊！！！
另外，启用右键菜单，新建文本文档，点击后一下子出现3个文件：新建文本文档、新建文本文档1、新建文本文档2，被吓到了！

型号名称：MacBook Pro
型号标识符：MacBookPro15,1
处理器名称：8-Core Intel Core i9
处理器速度：2.3 GHz
处理器数目：1
核总数：8
L2缓存（每个核）：256 KB
L3缓存：16 MB
超线程技术：已启用
内存：16 GB

**Comment by mtjo** [comment]
感谢反馈,
1.右键慢1-2秒这个问题我叫身边的朋友试了都没有出现方便可以邮件联系我调试一下
2.启用右键菜单新建文件是会检测当前目录是不是已经存在"新建文本文档"不会盖原文件
3.如果文件请使用最新版本看看还有没有上述问题

**Comment by mtjo** [comment]
https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化
