### ISSUE TITLE
这个软件最大的问题就是卡顿。

### ISSUE THREAD

**Issue by loveproe** [mtjo/MacStroke#16]
只要时间一长，就卡的不行。macos 11更明显。希望更新。。。

**Comment by mtjo** [comment]
> 只要时间一长，就卡的不行。macos 11更明显。希望更新。。。

感谢反馈
卡顿现在是什么,软件开发至今一直在使用,没感觉出卡顿,能说明一下怎么复现吗

**Comment by PromiseNev** [comment]
就是打开这软件时间一长,然后整个电脑感觉掉帧,然后关掉这软件,立马就恢复了, macOS 11  beta9    MacStroke 1.1.0

**Comment by mtjo** [comment]
> 就是打开这软件时间一长,然后整个电脑感觉掉帧,然后关掉这软件,立马就恢复了, macOS 11 beta9 MacStroke 1.1.0

感谢,
如果方便,请在卡的时候用monitor.app把内存的使用情况发截图发我一下 邮箱:mtjo@qq.com

**Comment by mtjo** [comment]
> 就是打开这软件时间一长,然后整个电脑感觉掉帧,然后关掉这软件,立马就恢复了, macOS 11 beta9 MacStroke 1.1.0

https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化

**Comment by mtjo** [comment]
https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化

**Comment by mtjo** [comment]
https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化
