### ISSUE TITLE
macOS 11中，导致系统卡顿

### ISSUE THREAD

**Issue by Joey0217** [mtjo/MacStroke#17]
Safari 14浏览器，发现经常卡的网页都关不掉，kernel_task进程占用非常高的内存（最高到过6G左右），Safari右键关闭页面很难调出，尝试结束macstroke进程，kernel_task进程恢复几百M的内存，Safari流畅如飞，再次打开macstroke短时间内无影响，几个小时后又会卡顿非常严重。

**Comment by Huansir325** [comment]
确实是，一直以为是新系统os11 BIG SUR的的什么bug，以前都是重启来解决，后来找到是这个软件的原因，关掉就不卡了，软件很好用，因为这个原因导致基本不能用了，希望改进，改进后会继续使用，辛苦！
症状是这样：长时间使用手势功能的时候，等累计使用手势约100-200次之后，系统掉帧，好像玩游戏显存爆掉了一样，感觉和内存关系不大吧，我一直用软件释放内存还是一样卡，但是关闭显示器再开（可以清除已用显存）也没用，只有关掉软件才好，退出软件后软件显示现存一下子清零，但是mac系统一直有这个毛病，显存满，但是不会卡。
ps：10.15系统好像没有这个问题，最起码感知不明显，11系统随时使用时间卡的系统几乎用不了了！

**Comment by mtjo** [comment]
> Safari 14浏览器，发现经常卡的网页都关不掉，kernel_task进程占用非常高的内存（最高到过6G左右），Safari右键关闭页面很难调出，尝试结束macstroke进程，kernel_task进程恢复几百M的内存，Safari流畅如飞，再次打开macstroke短时间内无影响，几个小时后又会卡顿非常严重。

感谢反馈,过几天升级big sur 后再针对优化

**Comment by Joey0217** [comment]
> > Safari 14浏览器，发现经常卡的网页都关不掉，kernel_task进程占用非常高的内存（最高到过6G左右），Safari右键关闭页面很难调出，尝试结束macstroke进程，kernel_task进程恢复几百M的内存，Safari流畅如飞，再次打开macstroke短时间内无影响，几个小时后又会卡顿非常严重。
> 
> 感谢反馈,过几天升级big sur 后再针对优化

期待大神更新，这款软件太实用了

**Comment by beck023** [comment]
非常好用的软件,谢谢大神的幸苦付出,最近刚升级了Big Sur, 就发现打开了Mac Stroke之后没多久,系统就会变得异常卡顿,连在链接上右键单击,弹出菜单都要好几秒,然后再iStat里发现运行Mac Stroke之后显存占用会从15%升到90%多,退出Mac Stroke后系统显存占用即可恢复正常,系统也不再卡顿.

**Comment by RyanMeng1** [comment]
请问针对bigsur有更新优化了吗

**Comment by mtjo** [comment]
> 请问针对bigsur有更新优化了吗

https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化

**Comment by mtjo** [comment]
> Safari 14浏览器，发现经常卡的网页都关不掉，kernel_task进程占用非常高的内存（最高到过6G左右），Safari右键关闭页面很难调出，尝试结束macstroke进程，kernel_task进程恢复几百M的内存，Safari流畅如飞，再次打开macstroke短时间内无影响，几个小时后又会卡顿非常严重。

https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化

**Comment by Joey0217** [comment]
> > Safari 14浏览器，发现经常卡的网页都关不掉，kernel_task进程占用非常高的内存（最高到过6G左右），Safari右键关闭页面很难调出，尝试结束macstroke进程，kernel_task进程恢复几百M的内存，Safari流畅如飞，再次打开macstroke短时间内无影响，几个小时后又会卡顿非常严重。
> 
> https://github.com/mtjo/MacStroke/releases/tag/2.0.0
> 新版本已经修复卡的问题,并单独针对bigsur进行了优化

谢谢大神更新，马上试试，新的M1可能马上到，希望也能完美支持，再次感谢

**Comment by mtjo** [comment]
https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化
