### ISSUE TITLE
你好,剪切板可以实现固定top内容吗

### ISSUE THREAD

**Issue by hecunsheng** [mtjo/MacStroke#19]
常用复制, 希望可以固定在top上面

**Comment by mtjo** [comment]
意思是把指定条目固定到列表前面吗？

**Comment by hecunsheng** [comment]
是的

**Comment by mtjo** [comment]
历史粘贴板添加了“置顶”功能，列表数据格式有变化，如果程序闪退，请操作 ： 常规->重置到预设 然后手退出程序再打开，或者删除 ~/Library/Preferences/net.mtjo.MacStroke.plist 重新打开软件
