### ISSUE TITLE
请问可以实现鼠标手势的功能吗?

### ISSUE THREAD

**Issue by beck023** [mtjo/MacStroke#20]
首先非常感谢大神的付出,做出了这么好用的软件,全局手势使用起来非常高效.
我有一个小小的需求不知能否实现,就是Safari的鼠标拖拽功能, 类似于easy drag to go这样的chrome 扩展.

**Comment by mtjo** [comment]
1. 软件手势可以兼容Safari 要实现类似于easy drag to go功能可以通过applescript实现，
2. 精力有险，不添加新功能了
