### ISSUE TITLE
开机自启无效

### ISSUE THREAD

**Issue by lqscript** [mtjo/MacStroke#24]
在偏好设置里勾选了自动启动,但是重启之后没有自动启动,并且设置面板上的勾选框变成未勾选了
macos 10.15.7

**Comment by mtjo** [comment]
我系统 11.5.1 ，刚刚测试是正常的，如果设置仍然不生效可以按以下步骤操作： 系统偏好设置->用户与群组->选择当前用户->登陆项->在列表中删除macstroke然后重新设置（或者删除后重新添加macstroke）

**Comment by lqscript** [comment]
公司的机器, 用户与群组 灰色的不能点击,是不是和这个有关

**Comment by mtjo** [comment]
是的，设置开机启动要管理员权限才可以

**Comment by lqscript** [comment]
可是我安装的mos、clashx这些就可以开机自启诶

**Comment by lqscript** [comment]
我晚上用家里的电脑试试

**Comment by mtjo** [comment]
你可以删除软件重新安装试试，我从10.13一直升级到现在都没出现过这个问题，也没有人反馈类似的问题

**Comment by lqscript** [comment]
找到原因了，我是下载的zip，然后解压之后就直接点开运行了，应该拖进应用程序目录，这样就可以了
软件很好用，给你点赞
