### ISSUE TITLE
11.5.2 访达扩展中的“在终端中打开”无效

### ISSUE THREAD

**Issue by v999v** [mtjo/MacStroke#26]
非常喜欢的一款软件, 希望越做越好, 已经离不开哈.

**Comment by mtjo** [comment]
感谢支持

> 非常喜欢的一款软件, 希望越做越好, 已经离不开哈.

针对以上反馈的问题刚刚在系统版本11.5.2 (20G95) 下测试功能没有问题，请查看是否给了相应的权限（隐私->自动化），再不行可以重装试试`brew reinstall --cask macstroke`

**Comment by v999v** [comment]
我重新试了, 准确的说应该在中文目录中打不开终端, 试了一个叫 openinterminal 的扩展插件是能行的.

**Comment by mtjo** [comment]
2.0.4 已更新
