### ISSUE TITLE
鼠标滚动方向

### ISSUE THREAD

**Issue by zmz125** [mtjo/MacStroke#28]
能不能添加一个鼠标滚动方向反转的设置，最好再加个平滑滚动

**Comment by mtjo** [comment]
> 能不能添加一个鼠标滚动方向反转的设置，最好再加个平滑滚动
这功能MAC的系统设置里本来就有的，你这是要我抄过来吗？

**Comment by zmz125** [comment]
不是的，因为系统里改了，触摸板手势滚动方向也会变，只想让第三方的鼠标改变滚动方向
