### ISSUE TITLE
无法使用移动快捷键（command + option + v）

### ISSUE THREAD

**Issue by Simon-Ace** [mtjo/MacStroke#34]
目前环境：
Monterey  12.1，m1 pro

问题现象：
开启 macstrock 程序后，无法使用移动快捷键（command + option + v）。关掉程序就好了

**Comment by mtjo** [comment]
> 目前环境： Monterey 12.1，m1 pro
> 
> 问题现象： 开启 macstrock 程序后，无法使用移动快捷键（command + option + v）。关掉程序就好了

### command + option + v 默认使用来做粘贴版管理，和你的系统设置有冲突，偏好设置->粘贴板 修改改成不冲突的快捷键就行，（command + option + v并不是系统默认的快捷键，应该是你自己设置的，你也可以在系统键盘设置里恢复系统默认快捷设置）

**Comment by Simon-Ace** [comment]
> > 目前环境： Monterey 12.1，m1 pro
> > 问题现象： 开启 macstrock 程序后，无法使用移动快捷键（command + option + v）。关掉程序就好了
> 
> ### command + option + v 默认使用来做粘贴版管理，和你的系统设置有冲突，偏好设置->粘贴板 修改改成不冲突的快捷键就行，（command + option + v并不是系统默认的快捷键，应该是你自己设置的，你也可以在系统键盘设置里恢复系统默认快捷设置）

已解决  感谢！
