### ISSUE TITLE
访达中 ⌥-Command-V 剪切快捷键失效

### ISSUE THREAD

**Issue by jg2017** [mtjo/MacStroke#37]
开启此软件后，热键Option-Command-V无反应，但Command-V可以

**Comment by mtjo** [comment]
> 开启此软件后，热键Option-Command-V无反应，但Command-V可以

你的情况应该和这位老哥一样，你参考一下
https://github.com/mtjo/MacStroke/issues/34

**Comment by jg2017** [comment]
> 

https://support.apple.com/zh-cn/HT201236，这确实是系统内置的快捷键，不太想改，不行就用右键吧。
还有个问题，就是开启这个软件时，如果登陆另外用户，其右键没反应

**Comment by jg2017** [comment]
> > 开启此软件后，热键Option-Command-V无反应，但Command-V可以
> 
> 你的情况应该和老哥一样，你看一下 #34

https://support.apple.com/zh-cn/HT201236，
这是官网，热键确实是系统内置的，不太想改，不行就用右键剪切吧。
还有，开启这个软件后，Mac打开另外用户，右键会没反应，只能先关闭软件，多用户切换才没问题。
