### ISSUE TITLE
macstroke 与android studio冲突

### ISSUE THREAD

**Issue by balala8** [mtjo/MacStroke#38]
在我的电脑上，mac os（big sur 11.6），Android studio 2021.2 与 mac stroke 相冲突。当开启mac stroke后，Android studio右键失效即点击右键无反应。但左键等均正常。关闭mac stroke后立刻恢复正常

**Comment by mtjo** [comment]
> 在我的电脑上，mac os（big sur 11.6），Android studio 2021.2 与 mac stroke 相冲突。当开启mac stroke后，Android studio右键失效即点击右键无反应。但左键等均正常。关闭mac stroke后立刻恢复正常

添加到模拟右键里就行，jetbrains 全家桶（Android studio 、idea、phpstrom ...）的工具都是 java 进程，右键逻辑不一样,将进程添加到模拟右键列表只就可以正常使用右键
