### ISSUE TITLE
MacOS最新的系统中存在bug

### ISSUE THREAD

**Issue by godfather1103** [mtjo/MacStroke#41]
详情见：
https://github.com/MacGesture/MacGesture/issues/123

**Comment by sqpool** [comment]
确实，我也发现了，可惜的是我抹盘重装了才发现的🥹

**Comment by mtjo** [comment]
> 详情见： [MacGesture/MacGesture#123](https://github.com/MacGesture/MacGesture/issues/123)

这个是 Mac OS 系统的 bug，我今天一路更新上来，12.4出现问题，更新到12.5就正常了，所以就不针对12.4修改版本修改了，大家更新到12.5就正常了

**Comment by godfather1103** [comment]
后面我试试看

**Comment by godfather1103** [comment]
好像12.5正常了，目前来看没问题
