### ISSUE TITLE
1.0.5 版本轨迹不消失

### ISSUE THREAD

**Issue by baonanhai** [mtjo/MacStroke#5]
我这边是用apple script 去启动finder，轨迹完成后会卡一秒左右，如果在这段时间内，继续移动，会导致留下鼠标轨迹，然后永远不消失（不重启的情况）。

软件版本 1.0.5
系统版本 10.14.6

补充下调用的脚本
tell application "Finder"
activate
end tell

**Comment by baonanhai** [comment]
补充下调用的脚本
tell application "Finder"
    activate
end tell

**Comment by mtjo** [comment]
> 我这边是用apple script 去启动finder，轨迹完成后会卡一秒左右，如果在这段时间内，继续移动，会导致留下鼠标轨迹，然后永远不消失（不重启的情况）。
> 
> 软件版本 1.0.5
> 系统版本 10.14.6
> 
> 补充下调用的脚本
> tell application "Finder"
> activate
> end tell

1.0.6 修复了,验证一下

**Comment by baonanhai** [comment]
已经弃用 apple script 了，这个破脚本调用东西太慢了

**Comment by mtjo** [comment]
新版本已经解决
