### ISSUE TITLE
手势提示文字：颜色太深了看不清，希望可以设置文字颜色

### ISSUE THREAD

**Issue by zhangciwu** [mtjo/MacStroke#50]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/3340597/201890449-6a7879b8-48f1-4014-8be3-e10a87c4fc70.png">
见截图

**Comment by mtjo** [comment]
> <img alt="image" width="288" src="https://user-images.githubusercontent.com/3340597/201890449-6a7879b8-48f1-4014-8be3-e10a87c4fc70.png">
> 
> 见截图

你使用的深色主题，字体是白色的你系统自动反转的颜色，修改系统设置就行了

**Comment by zhangciwu** [comment]
> > <img alt="image" width="288" src="https://user-images.githubusercontent.com/3340597/201890449-6a7879b8-48f1-4014-8be3-e10a87c4fc70.png">
> > 见截图
> 
> 你使用的深色主题，字体是白色的你系统自动反转的颜色，修改系统设置就行了

你好，你指的是什么设置呢？
目前我还是会用深色主题的
