### ISSUE TITLE
恳请添加声音控制，比如按住右键+滚轮上下 控制音量大小。

### ISSUE THREAD

**Issue by Axe-l** [mtjo/MacStroke#61]
恳请添加声音控制，比如按住右键滚轮上下控制音量。这是个非常方便的功能。

**Comment by llussy** [comment]
BetterMouse可以满足你的需求，我现在是同时使用BetterMouse和MacStroke.

**Comment by mtjo** [comment]
你直接给它加一个手势不就行了

**Comment by DemoJameson** [comment]
> 你直接给它加一个手势不就行了

MacStroke不支持右键+滚轮这种手势吧，起码我没找到如何设置的
