### ISSUE TITLE
自定义设置快捷键不起作用

### ISSUE THREAD

**Issue by liuzhaobo1999** [mtjo/MacStroke#62]
系统：黑苹果 macos 13.5.1
版本：2.0.5
两个问题：
1. 给某个手势设置热键：cmd+tab，设置不了（好像是现有生效的快捷键不能设置成功）
2. 调度中心的快捷键是：ctrl+上键，先禁用，才可以给手势设置成功，然后启用快捷键，但是鼠标滑动该手势，图标文本提示出来了，快捷键没有生效

哪位大哥给看看是什么问题？

**Comment by mtjo** [comment]
自己添加 applescript 就行了
参考这个 https://github.com/mtjo/MacStroke/issues/11#issuecomment-871129605
