### ISSUE TITLE
1.0.5 版本 intellij 下右键仍然不大好用

### ISSUE THREAD

**Issue by baonanhai** [mtjo/MacStroke#7]
右键时不时的不大好用。有时候灵，有时候不灵。

软件版本 1.0.5
系统版本 10.14.6

**Comment by mtjo** [comment]
> 右键时不时的不大好用。有时候灵，有时候不灵。
> 
> 软件版本 1.0.5
> 系统版本 10.14.6

1.0.8版本试试

**Comment by xqxian** [comment]
> > 右键时不时的不大好用。有时候灵，有时候不灵。
> > 软件版本 1.0.5
> > 系统版本 10.14.6
> 
> 1.0.8版本试试

你好，目前1.0.9版本在WebStorm 2020.2版本上还是有问题，只能先加入黑名单了，望修复，感谢~

**Comment by mtjo** [comment]
https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化
