### ISSUE TITLE
1.0.5 版本会导致卡顿

### ISSUE THREAD

**Issue by baonanhai** [mtjo/MacStroke#8]
在开机一段时间后，会明显的导致机器变卡，退出应用后重新打开会变好。

软件版本 1.0.5
系统版本 10.14.6

**Comment by baonanhai** [comment]
在屏幕合上后过段时间再次打开，遇到过几次明显卡顿，关了stroke重开就好

**Comment by baonanhai** [comment]
在使用外接屏幕，合上mac，然后后续断开外接屏幕，重新使用mac屏幕的时候，可能会卡成幻灯片

**Comment by mtjo** [comment]
> 在开机一段时间后，会明显的导致机器变卡，退出应用后重新打开会变好。
> 
> 软件版本 1.0.5
> 系统版本 10.14.6

1.0.5 版本有内存泄漏,1.0.6 版本已修复

**Comment by baonanhai** [comment]
那啥，笔记本屏幕闭合，使用外接屏幕的情况下，启动这个程序，然后随便画个手势。再打开笔记本屏幕，程序挂了。
![image](https://user-images.githubusercontent.com/1573149/70801613-4ecf9080-1dea-11ea-8a95-792122514371.png)

**Comment by mtjo** [comment]
> 谢谢修复，不过 1.0.6 还是有点问题。笔记本屏幕闭合，使用外接屏幕的情况下，启动这个程序，然后随便画个手势。再打开笔记本屏幕，程序挂了。
> ![image](https://user-images.githubusercontent.com/1573149/70801613-4ecf9080-1dea-11ea-8a95-792122514371.png)

修复了,有新问题请新开issues 方便跟进

**Comment by mtjo** [comment]
https://github.com/mtjo/MacStroke/releases/tag/2.0.0
新版本已经修复卡的问题,并单独针对bigsur进行了优化
