### ISSUE TITLE
MacGesture 2怎么和这个软件这么像啊？？？

### ISSUE THREAD

**Issue by piaoyizy** [mtjo/MacStroke#9]
MacGesture 2怎么和这个软件这么像啊？？？

**Comment by mtjo** [comment]
> MacGesture 2怎么和这个软件这么像啊？？？
应该说和MacGesture 1很像
3年前从MacGesture 1 fork 来的,后来MacGesture重构2.0版本源码基本上合不上了,和原<星落，说想念>作者沟通过,本来要全代码到他的 github 但我修改太多了,太多文件冲突了(源码我改了有70%),ui 设计上90%是他的,我这针对新mac 系统做了优化,添加了模拟右键,加了任意手势识别(记得当时在群里说我解决了任意手势识别,星落还给我发红包来的)
